export interface Exercise {
  id: string;
  name: string;
  category: "bodyweight" | "gym";
  description: string;
  muscles: string[];
}

export const exercises: Exercise[] = [
  // GYM EXERCISES (50)
  {
    id: "gym-1",
    name: "Barbell Bench Press",
    category: "gym",
    description: "Lower bar to chest, press upward.",
    muscles: ["Chest (60%)", "Triceps (25%)", "Shoulders (15%)"],
  },
  {
    id: "gym-2",
    name: "Incline Bench Press",
    category: "gym",
    description: "Press bar from upper chest upward.",
    muscles: ["Chest (55%)", "Shoulders (30%)", "Triceps (15%)"],
  },
  {
    id: "gym-3",
    name: "Decline Bench Press",
    category: "gym",
    description: "Press bar upward on decline bench.",
    muscles: ["Chest (65%)", "Triceps (25%)", "Shoulders (10%)"],
  },
  {
    id: "gym-4",
    name: "Cable Chest Fly",
    category: "gym",
    description: "Bring handles together in front.",
    muscles: ["Chest (80%)", "Shoulders (20%)"],
  },
  {
    id: "gym-5",
    name: "Pec Deck Machine",
    category: "gym",
    description: "Close arms together on machine.",
    muscles: ["Chest (85%)", "Shoulders (15%)"],
  },
  {
    id: "gym-6",
    name: "Lat Pulldown",
    category: "gym",
    description: "Pull bar to chest.",
    muscles: ["Back (70%)", "Biceps (20%)", "Shoulders (10%)"],
  },
  {
    id: "gym-7",
    name: "Pull-ups (Assisted)",
    category: "gym",
    description: "Pull body up to bar.",
    muscles: ["Back (65%)", "Biceps (25%)", "Core (10%)"],
  },
  {
    id: "gym-8",
    name: "Seated Cable Row",
    category: "gym",
    description: "Pull handle to torso.",
    muscles: ["Back (70%)", "Biceps (20%)", "Shoulders (10%)"],
  },
  {
    id: "gym-9",
    name: "Barbell Row",
    category: "gym",
    description: "Pull bar to stomach.",
    muscles: ["Back (75%)", "Biceps (15%)", "Core (10%)"],
  },
  {
    id: "gym-10",
    name: "T-Bar Row",
    category: "gym",
    description: "Pull weight toward chest.",
    muscles: ["Back (75%)", "Biceps (15%)", "Core (10%)"],
  },
  {
    id: "gym-11",
    name: "Shoulder Press Machine",
    category: "gym",
    description: "Press handles overhead.",
    muscles: ["Shoulders (70%)", "Triceps (30%)"],
  },
  {
    id: "gym-12",
    name: "Dumbbell Shoulder Press",
    category: "gym",
    description: "Press dumbbells overhead.",
    muscles: ["Shoulders (65%)", "Triceps (35%)"],
  },
  {
    id: "gym-13",
    name: "Lateral Raise",
    category: "gym",
    description: "Raise arms to sides.",
    muscles: ["Shoulders (90%)", "Traps (10%)"],
  },
  {
    id: "gym-14",
    name: "Front Raise",
    category: "gym",
    description: "Lift weight forward.",
    muscles: ["Shoulders (85%)", "Chest (15%)"],
  },
  {
    id: "gym-15",
    name: "Rear Delt Fly",
    category: "gym",
    description: "Open arms backward.",
    muscles: ["Shoulders (70%)", "Back (30%)"],
  },
  {
    id: "gym-16",
    name: "Barbell Curl",
    category: "gym",
    description: "Curl bar upward.",
    muscles: ["Biceps (90%)", "Forearms (10%)"],
  },
  {
    id: "gym-17",
    name: "Hammer Curl",
    category: "gym",
    description: "Curl with neutral grip.",
    muscles: ["Biceps (70%)", "Forearms (30%)"],
  },
  {
    id: "gym-18",
    name: "Cable Curl",
    category: "gym",
    description: "Curl cable toward chest.",
    muscles: ["Biceps (85%)", "Forearms (15%)"],
  },
  {
    id: "gym-19",
    name: "Tricep Pushdown",
    category: "gym",
    description: "Push bar downward.",
    muscles: ["Triceps (90%)", "Forearms (10%)"],
  },
  {
    id: "gym-20",
    name: "Skull Crushers",
    category: "gym",
    description: "Lower bar to forehead.",
    muscles: ["Triceps (90%)", "Shoulders (10%)"],
  },
  {
    id: "gym-21",
    name: "Leg Press",
    category: "gym",
    description: "Push platform away.",
    muscles: ["Quads (60%)", "Glutes (25%)", "Hamstrings (15%)"],
  },
  {
    id: "gym-22",
    name: "Barbell Squat",
    category: "gym",
    description: "Lower hips, stand up.",
    muscles: ["Quads (50%)", "Glutes (30%)", "Core (20%)"],
  },
  {
    id: "gym-23",
    name: "Hack Squat",
    category: "gym",
    description: "Squat on machine.",
    muscles: ["Quads (65%)", "Glutes (25%)", "Hamstrings (10%)"],
  },
  {
    id: "gym-24",
    name: "Lunges (Dumbbell)",
    category: "gym",
    description: "Step forward, lower body.",
    muscles: ["Quads (50%)", "Glutes (30%)", "Hamstrings (20%)"],
  },
  {
    id: "gym-25",
    name: "Leg Extension",
    category: "gym",
    description: "Extend legs upward.",
    muscles: ["Quads (90%)"],
  },
  {
    id: "gym-26",
    name: "Leg Curl",
    category: "gym",
    description: "Curl legs backward.",
    muscles: ["Hamstrings (90%)"],
  },
  {
    id: "gym-27",
    name: "Romanian Deadlift",
    category: "gym",
    description: "Lower bar with straight legs.",
    muscles: ["Hamstrings (50%)", "Glutes (30%)", "Back (20%)"],
  },
  {
    id: "gym-28",
    name: "Deadlift",
    category: "gym",
    description: "Lift bar from ground.",
    muscles: ["Back (40%)", "Glutes (30%)", "Hamstrings (30%)"],
  },
  {
    id: "gym-29",
    name: "Calf Raise (Machine)",
    category: "gym",
    description: "Raise heels up.",
    muscles: ["Calves (100%)"],
  },
  {
    id: "gym-30",
    name: "Standing Calf Raise",
    category: "gym",
    description: "Lift heels standing.",
    muscles: ["Calves (100%)"],
  },
  {
    id: "gym-31",
    name: "Cable Crunch",
    category: "gym",
    description: "Crunch downward.",
    muscles: ["Abs (90%)"],
  },
  {
    id: "gym-32",
    name: "Hanging Leg Raise",
    category: "gym",
    description: "Lift legs up.",
    muscles: ["Abs (80%)", "Hip Flexors (20%)"],
  },
  {
    id: "gym-33",
    name: "Ab Machine Crunch",
    category: "gym",
    description: "Crunch forward.",
    muscles: ["Abs (90%)"],
  },
  {
    id: "gym-34",
    name: "Russian Twist (Weighted)",
    category: "gym",
    description: "Twist torso side to side.",
    muscles: ["Abs (70%)", "Obliques (30%)"],
  },
  {
    id: "gym-35",
    name: "Plank (Weighted)",
    category: "gym",
    description: "Hold straight body.",
    muscles: ["Core (100%)"],
  },
  {
    id: "gym-36",
    name: "Smith Machine Squat",
    category: "gym",
    description: "Squat using Smith bar.",
    muscles: ["Quads (55%)", "Glutes (30%)", "Core (15%)"],
  },
  {
    id: "gym-37",
    name: "Smith Machine Bench Press",
    category: "gym",
    description: "Press fixed bar upward.",
    muscles: ["Chest (60%)", "Triceps (25%)", "Shoulders (15%)"],
  },
  {
    id: "gym-38",
    name: "Cable Lateral Raise",
    category: "gym",
    description: "Raise cable to side.",
    muscles: ["Shoulders (90%)"],
  },
  {
    id: "gym-39",
    name: "Face Pull",
    category: "gym",
    description: "Pull rope to face.",
    muscles: ["Shoulders (60%)", "Back (40%)"],
  },
  {
    id: "gym-40",
    name: "Upright Row",
    category: "gym",
    description: "Pull bar to chin.",
    muscles: ["Shoulders (60%)", "Traps (40%)"],
  },
  {
    id: "gym-41",
    name: "Hip Thrust",
    category: "gym",
    description: "Lift hips upward.",
    muscles: ["Glutes (80%)", "Hamstrings (20%)"],
  },
  {
    id: "gym-42",
    name: "Glute Kickback (Cable)",
    category: "gym",
    description: "Kick leg backward.",
    muscles: ["Glutes (90%)"],
  },
  {
    id: "gym-43",
    name: "Chest Dips",
    category: "gym",
    description: "Lower body, push up.",
    muscles: ["Chest (50%)", "Triceps (40%)", "Shoulders (10%)"],
  },
  {
    id: "gym-44",
    name: "Assisted Dips",
    category: "gym",
    description: "Push body up on machine.",
    muscles: ["Triceps (60%)", "Chest (30%)", "Shoulders (10%)"],
  },
  {
    id: "gym-45",
    name: "Incline Dumbbell Curl",
    category: "gym",
    description: "Curl while seated back.",
    muscles: ["Biceps (85%)"],
  },
  {
    id: "gym-46",
    name: "Preacher Curl",
    category: "gym",
    description: "Curl over pad.",
    muscles: ["Biceps (90%)"],
  },
  {
    id: "gym-47",
    name: "Reverse Curl",
    category: "gym",
    description: "Curl with overhand grip.",
    muscles: ["Forearms (70%)", "Biceps (30%)"],
  },
  {
    id: "gym-48",
    name: "Farmer’s Walk",
    category: "gym",
    description: "Walk holding weights.",
    muscles: ["Forearms (40%)", "Core (30%)", "Shoulders (30%)"],
  },
  {
    id: "gym-49",
    name: "Shrugs",
    category: "gym",
    description: "Lift shoulders up.",
    muscles: ["Traps (100%)"],
  },
  {
    id: "gym-50",
    name: "Back Extension",
    category: "gym",
    description: "Raise torso upward.",
    muscles: ["Lower Back (70%)", "Glutes (30%)"],
  },

  // HOME EXERCISES (50)
  {
    id: "home-1",
    name: "Push-ups",
    category: "bodyweight",
    description: "Lower chest to floor, push up.",
    muscles: ["Chest (50%)", "Triceps (30%)", "Shoulders (20%)"],
  },
  {
    id: "home-2",
    name: "Incline Push-ups",
    category: "bodyweight",
    description: "Hands elevated, push up.",
    muscles: ["Chest (55%)", "Shoulders (25%)", "Triceps (20%)"],
  },
  {
    id: "home-3",
    name: "Decline Push-ups",
    category: "bodyweight",
    description: "Feet elevated, push up.",
    muscles: ["Chest (60%)", "Shoulders (30%)", "Triceps (10%)"],
  },
  {
    id: "home-4",
    name: "Diamond Push-ups",
    category: "bodyweight",
    description: "Hands close, push up.",
    muscles: ["Triceps (60%)", "Chest (30%)", "Shoulders (10%)"],
  },
  {
    id: "home-5",
    name: "Wide Push-ups",
    category: "bodyweight",
    description: "Wide hands, push up.",
    muscles: ["Chest (70%)", "Shoulders (20%)", "Triceps (10%)"],
  },
  {
    id: "home-6",
    name: "Pike Push-ups",
    category: "bodyweight",
    description: "Push in pike position.",
    muscles: ["Shoulders (70%)", "Triceps (30%)"],
  },
  {
    id: "home-7",
    name: "Pull-ups",
    category: "bodyweight",
    description: "Pull body up.",
    muscles: ["Back (65%)", "Biceps (25%)", "Core (10%)"],
  },
  {
    id: "home-8",
    name: "Chin-ups",
    category: "bodyweight",
    description: "Pull with underhand grip.",
    muscles: ["Biceps (50%)", "Back (40%)", "Core (10%)"],
  },
  {
    id: "home-9",
    name: "Bodyweight Squat",
    category: "bodyweight",
    description: "Lower and stand.",
    muscles: ["Quads (50%)", "Glutes (30%)", "Hamstrings (20%)"],
  },
  {
    id: "home-10",
    name: "Jump Squat",
    category: "bodyweight",
    description: "Squat then jump.",
    muscles: ["Quads (50%)", "Glutes (30%)", "Cardio (20%)"],
  },
  {
    id: "home-11",
    name: "Lunges",
    category: "bodyweight",
    description: "Step and lower.",
    muscles: ["Quads (50%)", "Glutes (30%)", "Hamstrings (20%)"],
  },
  {
    id: "home-12",
    name: "Bulgarian Split Squat",
    category: "bodyweight",
    description: "Rear foot elevated.",
    muscles: ["Quads (50%)", "Glutes (40%)", "Balance (10%)"],
  },
  {
    id: "home-13",
    name: "Glute Bridge",
    category: "bodyweight",
    description: "Lift hips upward.",
    muscles: ["Glutes (80%)", "Hamstrings (20%)"],
  },
  {
    id: "home-14",
    name: "Hip Thrust (Home)",
    category: "bodyweight",
    description: "Raise hips on bench.",
    muscles: ["Glutes (85%)"],
  },
  {
    id: "home-15",
    name: "Calf Raises",
    category: "bodyweight",
    description: "Lift heels up.",
    muscles: ["Calves (100%)"],
  },
  {
    id: "home-16",
    name: "Wall Sit",
    category: "bodyweight",
    description: "Hold squat on wall.",
    muscles: ["Quads (70%)", "Glutes (30%)"],
  },
  {
    id: "home-17",
    name: "Plank",
    category: "bodyweight",
    description: "Hold straight body.",
    muscles: ["Core (100%)"],
  },
  {
    id: "home-18",
    name: "Side Plank",
    category: "bodyweight",
    description: "Hold on one side.",
    muscles: ["Obliques (80%)", "Core (20%)"],
  },
  {
    id: "home-19",
    name: "Mountain Climbers",
    category: "bodyweight",
    description: "Run in plank.",
    muscles: ["Core (50%)", "Cardio (50%)"],
  },
  {
    id: "home-20",
    name: "Leg Raises",
    category: "bodyweight",
    description: "Lift legs up.",
    muscles: ["Abs (80%)", "Hip Flexors (20%)"],
  },
  {
    id: "home-21",
    name: "Sit-ups",
    category: "bodyweight",
    description: "Lift torso upward.",
    muscles: ["Abs (80%)", "Hip Flexors (20%)"],
  },
  {
    id: "home-22",
    name: "Crunches",
    category: "bodyweight",
    description: "Short crunch upward.",
    muscles: ["Abs (90%)"],
  },
  {
    id: "home-23",
    name: "Bicycle Crunch",
    category: "bodyweight",
    description: "Twist elbows to knees.",
    muscles: ["Abs (70%)", "Obliques (30%)"],
  },
  {
    id: "home-24",
    name: "Russian Twist",
    category: "bodyweight",
    description: "Twist torso.",
    muscles: ["Abs (70%)", "Obliques (30%)"],
  },
  {
    id: "home-25",
    name: "Superman",
    category: "bodyweight",
    description: "Lift arms and legs.",
    muscles: ["Lower Back (60%)", "Glutes (40%)"],
  },
  {
    id: "home-26",
    name: "Burpees",
    category: "bodyweight",
    description: "Squat, jump, push-up.",
    muscles: ["Full Body (100%)"],
  },
  {
    id: "home-27",
    name: "High Knees",
    category: "bodyweight",
    description: "Run lifting knees.",
    muscles: ["Cardio (70%)", "Legs (30%)"],
  },
  {
    id: "home-28",
    name: "Jumping Jacks",
    category: "bodyweight",
    description: "Jump with arms spread.",
    muscles: ["Cardio (80%)", "Full Body (20%)"],
  },
  {
    id: "home-29",
    name: "Bear Crawl",
    category: "bodyweight",
    description: "Crawl on hands/feet.",
    muscles: ["Core (40%)", "Shoulders (30%)", "Legs (30%)"],
  },
  {
    id: "home-30",
    name: "Crab Walk",
    category: "bodyweight",
    description: "Walk facing upward.",
    muscles: ["Core (30%)", "Arms (30%)", "Legs (40%)"],
  },
  {
    id: "home-31",
    name: "Chair Dips",
    category: "bodyweight",
    description: "Lower on chair.",
    muscles: ["Triceps (70%)", "Chest (20%)", "Shoulders (10%)"],
  },
  {
    id: "home-32",
    name: "Decline Sit-ups",
    category: "bodyweight",
    description: "Sit-up on decline.",
    muscles: ["Abs (85%)"],
  },
  {
    id: "home-33",
    name: "Reverse Crunch",
    category: "bodyweight",
    description: "Lift hips upward.",
    muscles: ["Abs (90%)"],
  },
  {
    id: "home-34",
    name: "Plank Shoulder Taps",
    category: "bodyweight",
    description: "Tap shoulders in plank.",
    muscles: ["Core (70%)", "Shoulders (30%)"],
  },
  {
    id: "home-35",
    name: "Wall Push-ups",
    category: "bodyweight",
    description: "Push against wall.",
    muscles: ["Chest (50%)", "Triceps (30%)", "Shoulders (20%)"],
  },
  {
    id: "home-36",
    name: "Towel Rows",
    category: "bodyweight",
    description: "Pull using towel.",
    muscles: ["Back (70%)", "Biceps (30%)"],
  },
  {
    id: "home-37",
    name: "Isometric Squat Hold",
    category: "bodyweight",
    description: "Hold squat position.",
    muscles: ["Quads (70%)"],
  },
  {
    id: "home-38",
    name: "Skater Jumps",
    category: "bodyweight",
    description: "Jump side to side.",
    muscles: ["Legs (60%)", "Cardio (40%)"],
  },
  {
    id: "home-39",
    name: "Step-ups",
    category: "bodyweight",
    description: "Step on platform.",
    muscles: ["Quads (50%)", "Glutes (30%)", "Hamstrings (20%)"],
  },
  {
    id: "home-40",
    name: "Box Jumps",
    category: "bodyweight",
    description: "Jump onto surface.",
    muscles: ["Legs (60%)", "Power (40%)"],
  },
  {
    id: "home-41",
    name: "Hollow Hold",
    category: "bodyweight",
    description: "Hold curved position.",
    muscles: ["Core (100%)"],
  },
  {
    id: "home-42",
    name: "V-Ups",
    category: "bodyweight",
    description: "Lift legs and torso.",
    muscles: ["Abs (90%)"],
  },
  {
    id: "home-43",
    name: "Flutter Kicks",
    category: "bodyweight",
    description: "Kick legs alternately.",
    muscles: ["Abs (80%)"],
  },
  {
    id: "home-44",
    name: "Scissor Kicks",
    category: "bodyweight",
    description: "Cross legs in air.",
    muscles: ["Abs (80%)"],
  },
  {
    id: "home-45",
    name: "Arm Circles",
    category: "bodyweight",
    description: "Rotate arms.",
    muscles: ["Shoulders (80%)"],
  },
  {
    id: "home-46",
    name: "Handstand Hold",
    category: "bodyweight",
    description: "Hold upside down.",
    muscles: ["Shoulders (70%)", "Core (30%)"],
  },
  {
    id: "home-47",
    name: "Wall Walk",
    category: "bodyweight",
    description: "Walk up wall.",
    muscles: ["Shoulders (70%)", "Core (30%)"],
  },
  {
    id: "home-48",
    name: "Resistance Band Curl",
    category: "bodyweight",
    description: "Curl band upward.",
    muscles: ["Biceps (85%)"],
  },
  {
    id: "home-49",
    name: "Resistance Band Squat",
    category: "bodyweight",
    description: "Squat with band.",
    muscles: ["Quads (50%)", "Glutes (30%)", "Hamstrings (20%)"],
  },
  {
    id: "home-50",
    name: "Resistance Band Row",
    category: "bodyweight",
    description: "Pull band toward you.",
    muscles: ["Back (70%)", "Biceps (30%)"],
  },
];
